In [1]:
import torch

# Create a tensor
x = torch.tensor([1, 2, 3])
y = torch.ones_like(x)  # Creates a tensor of ones with the same shape as x

# Basic tensor operations
z = x + y  # Element-wise addition
w = torch.matmul(x, y)  # Matrix multiplication (dot product if 1D)


/Users/s/PhD/gitrepo/Torch-Practice/venv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
# Example with autograd
x = torch.tensor([1.0, 2.0], requires_grad=True)
y = x**2
z = y.sum()

# Compute gradients
z.backward()

# Access gradients
print(x.grad)  # Gradient of z with respect to x


tensor([2., 4.])


In [3]:
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.layer1 = nn.Linear(10, 5)  # Input: 10 features, Output: 5 features
        self.layer2 = nn.ReLU()
        self.layer3 = nn.Linear(5, 1)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x


In [4]:
import torch.optim as optim

# Model and optimizer
model = SimpleNN()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Zero the gradients, perform a backward pass, and update weights
optimizer.zero_grad()  # Clears old gradients
output = model(torch.randn(1, 10))  # Example input
loss = output.sum()  # Just an example loss function
loss.backward()
optimizer.step()  # Updates parameters


In [6]:
import gpytorch

class GPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(GPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.RBFKernel()
        self.likelihood = likelihood

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# Training a GP model with GPytorch involves defining a likelihood and optimizing the model parameters using PyTorch's optimizers.


In [7]:
import torch
from botorch.models import SingleTaskGP
from botorch.optim import optimize_acqf

# Define some data points and a GP model
train_x = torch.rand(10, 1)  # 10 data points, 1 feature each
train_y = torch.sin(train_x)

# Build a single-task GP model
gp = SingleTaskGP(train_x, train_y)

# Define an acquisition function (e.g., Expected Improvement)
# and optimize it to find the next sample
from botorch.acquisition import ExpectedImprovement
from botorch.optim import optimize_acqf

acqf = ExpectedImprovement(gp, best_f=train_y.max())
next_point, _ = optimize_acqf(acqf, bounds=torch.tensor([[0.], [1.]]), num_restarts=5, raw_samples=20)


/Users/s/PhD/gitrepo/Torch-Practice/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/_4/f_rgwft14s14_j1xnpz_zn7c0000gn/T/ipykernel_12979/3905559278.py:10: InputDataWarning: The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444
  gp = SingleTaskGP(train_x, train_y)
/Users/s/PhD/gitrepo/Torch-Practice/venv/lib/python3.13/site-packages/botorch/acquisition/analytic.py:331: NumericsWarning: ExpectedImprovement has known numerical issues that lead to suboptimal optimization performance. It is strongly recommended to simply replace

	 ExpectedImprovement 	 --> 	 LogExpectedImprovement 

instead, which fix

TypeError: optimize_acqf() missing 1 required positional argument: 'q'

In [4]:
import torch
from botorch.models import SingleTaskGP
from botorch.acquisition import ExpectedImprovement
from botorch.optim import optimize_acqf

# Define some data points and a GP model
train_x = torch.rand(10, 1)  # 10 data points, 1 feature each
train_y = torch.sin(train_x)

# Build a single-task GP model
gp = SingleTaskGP(train_x, train_y)

# Define an acquisition function (e.g., Expected Improvement)
acqf = ExpectedImprovement(gp, best_f=train_y.max())

# Specify the number of candidates to optimize over
q = 1  # For single candidate optimization

#define boudnds
bounds = torch.tensor([[0.],[1.]])

# Optimize the acquisition function to find the next sample
next_point, _ = optimize_acqf(
    acqf, 
    bounds=bounds,  #pass
    num_restarts=5,  # Number of random restarts for optimization
    raw_samples=20,  # Number of raw candidates to sample before optimization
    q=q  # Number of candidates to optimize over at once
)

print(next_point)


tensor([[1.]])


/var/folders/_4/f_rgwft14s14_j1xnpz_zn7c0000gn/T/ipykernel_13358/1056962898.py:11: InputDataWarning: The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444
  gp = SingleTaskGP(train_x, train_y)
/Users/s/PhD/gitrepo/Torch-Practice/venv/lib/python3.13/site-packages/botorch/acquisition/analytic.py:331: NumericsWarning: ExpectedImprovement has known numerical issues that lead to suboptimal optimization performance. It is strongly recommended to simply replace

	 ExpectedImprovement 	 --> 	 LogExpectedImprovement 

instead, which fixes the issues and has the same API. See https://arxiv.org/abs/2310.20708 for details.
  legacy_ei_numerics_warning(legacy_name=type(self).__name__)


In [5]:
import torch
from botorch.models import SingleTaskGP
from botorch.acquisition import ExpectedImprovement
from botorch.optim import optimize_acqf

# Define some data points and a GP model
train_x = torch.rand(10, 1)  # 10 data points, 1 feature each
train_y = torch.sin(train_x)

# Build a single-task GP model
gp = SingleTaskGP(train_x, train_y)

# Define an acquisition function (e.g., Expected Improvement)
acqf = ExpectedImprovement(gp, best_f=train_y.max())

# Specify the number of candidates to optimize over
q = 1  # For single candidate optimization

# Define the bounds of the search space (ensure correct shape: 2 x 1)
bounds = torch.tensor([[0.], [1.]])  # Lower and upper bounds in the 1D space

# Optimize the acquisition function to find the next sample
next_point, _ = optimize_acqf(
    acqf, 
    bounds=bounds,  # Pass bounds here
    num_restarts=5,  # Number of random restarts for optimization
    raw_samples=20,  # Number of raw candidates to sample before optimization
    q=q  # Number of candidates to optimize over at once
)

print(next_point)


tensor([[1.]])


/var/folders/_4/f_rgwft14s14_j1xnpz_zn7c0000gn/T/ipykernel_13358/782265510.py:11: InputDataWarning: The model inputs are of type torch.float32. It is strongly recommended to use double precision in BoTorch, as this improves both precision and stability and can help avoid numerical errors. See https://github.com/pytorch/botorch/discussions/1444
  gp = SingleTaskGP(train_x, train_y)
/Users/s/PhD/gitrepo/Torch-Practice/venv/lib/python3.13/site-packages/botorch/acquisition/analytic.py:331: NumericsWarning: ExpectedImprovement has known numerical issues that lead to suboptimal optimization performance. It is strongly recommended to simply replace

	 ExpectedImprovement 	 --> 	 LogExpectedImprovement 

instead, which fixes the issues and has the same API. See https://arxiv.org/abs/2310.20708 for details.
  legacy_ei_numerics_warning(legacy_name=type(self).__name__)


In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
import gpytorch
from matplotlib import pyplot as plt

# Step 1: Define a 2-layer Neural Network model
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(1, 50)  # 1 input feature, 50 output features
        self.fc2 = nn.Linear(50, 1)  # 50 input features, 1 output feature

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # Apply ReLU activation function
        x = self.fc2(x)
        return x

# Step 2: Define a Gaussian Process Model using GPytorch
class GPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(GPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()  # Constant Mean function
        self.covar_module = gpytorch.kernels.RBFKernel()  # RBF Kernel
        self.likelihood = likelihood

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# Step 3: Generate toy training data
train_x = torch.linspace(0, 1, 10).reshape(-1, 1)  # 10 training points
train_y = torch.sin(train_x * (2 * torch.pi)) + 0.2 * torch.randn_like(train_x)  # Sine curve + noise

# Step 4: Define the Neural Network Model and Train It
nn_model = SimpleNN()
nn_optimizer = optim.Adam(nn_model.parameters(), lr=0.01)
nn_loss_fn = nn.MSELoss()

# Train the neural network
num_epochs = 200
for epoch in range(num_epochs):
    nn_model.train()
    nn_optimizer.zero_grad()
    nn_pred = nn_model(train_x)
    nn_loss = nn_loss_fn(nn_pred, train_y)
    nn_loss.backward()
    nn_optimizer.step()

    if epoch % 50 == 0:
        print(f"NN Epoch {epoch}, Loss: {nn_loss.item()}")

# Step 5: Define the GP Model and Train It
likelihood = gpytorch.likelihoods.GaussianLikelihood()
gp_model = GPModel(train_x, train_y, likelihood)

# Set up optimizer and loss function for GP
gp_optimizer = torch.optim.Adam(gp_model.parameters(), lr=0.1)
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, gp_model)

# Train the GP model
gp_model.train()
likelihood.train()

for epoch in range(100):
    gp_optimizer.zero_grad()
    output = gp_model(train_x)
    # Ensure the output is a scalar and that the loss can be backpropagated
    if output.mean.shape != torch.Size([]):  # Check if it's not scalar
        print("Warning: Output is not scalar. Shape:", output.mean.shape)

    loss = -mll(output, train_y)

    # Ensure loss is scalar
    if isinstance(loss, torch.Tensor) and loss.shape != torch.Size([]):
        print("Warning: Loss is not scalar. Shape:", loss.shape)

    loss.backward()
    gp_optimizer.step()

    if epoch % 20 == 0:
        print(f"GP Epoch {epoch}, Loss: {loss.item()}")

# Step 6: Evaluate both models and make predictions
# Neural Network Prediction
nn_model.eval()
nn_pred = nn_model(train_x).detach()

# Gaussian Process Prediction
gp_model.eval()
likelihood.eval()

with torch.no_grad():
    gp_pred = likelihood(gp_model(train_x))

# Step 7: Plot the Results
# Plotting both Neural Network and GP predictions with confidence intervals
test_x = torch.linspace(0, 1, 1000).reshape(-1, 1)

# Neural Network Predictions for test points
nn_test_pred = nn_model(test_x).detach()

# GP Predictions for test points
with torch.no_grad():
    gp_test_pred = likelihood(gp_model(test_x))

# Plot Training Data
plt.figure(figsize=(10, 6))

# Neural Network Predictions
plt.subplot(2, 1, 1)
plt.plot(train_x.numpy(), train_y.numpy(), 'kx', label="Training Data")
plt.plot(test_x.numpy(), nn_test_pred.numpy(), 'r', label="NN Prediction")
plt.title("Neural Network Prediction vs Training Data")
plt.legend()

# GP Predictions
plt.subplot(2, 1, 2)
mean = gp_test_pred.mean
lower, upper = gp_test_pred.confidence_region()
plt.plot(train_x.numpy(), train_y.numpy(), 'kx', label="Training Data")
plt.plot(test_x.numpy(), mean.numpy(), 'r', label="GP Prediction Mean")
plt.fill_between(test_x.numpy(), lower.numpy(), upper.numpy(), color='red', alpha=0.2, label="GP Confidence Region")
plt.title("Gaussian Process Prediction vs Training Data")
plt.legend()

plt.tight_layout()
plt.show()

# Step 8: Compare Metrics
# Calculate MSE for both models
nn_mse = nn_loss_fn(nn_pred, train_y).item()
gp_mse = ((gp_pred.mean - train_y) ** 2).mean().item()

print(f"Neural Network MSE: {nn_mse}")
print(f"Gaussian Process MSE: {gp_mse}")


NN Epoch 0, Loss: 0.5697742104530334
NN Epoch 50, Loss: 0.2620859742164612
NN Epoch 100, Loss: 0.1349755823612213
NN Epoch 150, Loss: 0.03566164895892143


RuntimeError: grad can be implicitly created only for scalar outputs